CREATE TABLE IF NOT EXISTS listing_details (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID NOT NULL UNIQUE REFERENCES listings(id) ON DELETE CASCADE,
    fuel_type VARCHAR(50),
    transmission_type VARCHAR(50),
    body_type VARCHAR(50),
    drive_type VARCHAR(50),
    engine_power INTEGER,
    engine_volume INTEGER,
    kilometers INTEGER,
    year INTEGER,
    color VARCHAR(50),
    heavy_damage BOOLEAN DEFAULT false,
    front_bumper VARCHAR(50),
    front_hood VARCHAR(50),
    roof VARCHAR(50),
    front_right_door VARCHAR(50),
    rear_right_door VARCHAR(50),
    front_left_mudguard VARCHAR(50),
    front_left_door VARCHAR(50),
    rear_left_door VARCHAR(50),
    rear_left_mudguard VARCHAR(50),
    rear_bumper VARCHAR(50),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
); 