name: Deploy Container
on:
  push:
    branches: [ development ]

env:
  GIN_MODE: debug
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
  HOST: ${{ secrets.HOST }}
  PORT: ${{ secrets.PORT }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWD: ${{ secrets.DB_PASSWD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_HOST: ${{ secrets.DB_HOST }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  SMTP_HOST: ${{ secrets.SMTP_HOST }}
  SMTP_PORT: ${{ secrets.SMTP_PORT }}
  SMTP_USER: ${{ secrets.SMTP_USER }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  CAR_RECOGNITION_API_URL: ${{ secrets.CAR_RECOGNITION_API_URL }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_REDIRECT_URL: ${{ secrets.GOOGLE_REDIRECT_URL }}
  GOOGLE_SCOPES: ${{ secrets.GOOGLE_SCOPES }}
  OAUTH2_STATE: ${{ secrets.OAUTH2_STATE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./src/api
  docker_deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}
  
  deploy:
    needs: docker_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "🚀 Pulling image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}"
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}

            echo "🧹 Stopping and removing old container if exists..."
            docker stop carwisegw || true
            docker rm carwisegw || true

            echo "🗑️ Pruning old images..."
            docker image prune -f

             echo "📁 Creating secure directory for .env file..."
            mkdir -p ~/.carwisegw/
            
            # Create the .env file with restricted permissions
            # 'cat' ile dosyayı oluşturup, 'chmod 600' ile sadece dosya sahibinin okuma/yazma izni olmasını sağlıyoruz.
            echo "📝 Creating .env file with restricted permissions..."
            cat <<EOF > ~/.carwisegw/carwisegw.env
            GIN_MODE=debug
            HOST=${{ env.HOST }}
            PORT=${{ env.PORT }}
            JWT_SECRET=${{ env.JWT_SECRET }}
            DB_USER=${{ env.DB_USER }}
            DB_PASSWD=${{ env.DB_PASSWD }}
            DB_NAME=${{ env.DB_NAME }}
            DB_PORT=${{ env.DB_PORT }}
            DB_HOST=${{ env.DB_HOST }}
            REDIS_HOST=${{ env.REDIS_HOST }}
            REDIS_PASSWORD=${{ env.REDIS_PASSWORD }}
            REDIS_PORT=${{ env.REDIS_PORT }}
            SMTP_HOST=${{ env.SMTP_HOST }}
            SMTP_PORT=${{ env.SMTP_PORT }}
            SMTP_USER=${{ env.SMTP_USER }}
            SMTP_PASSWORD=${{ env.SMTP_PASSWORD }}
            CAR_RECOGNITION_API_URL=${{ env.CAR_RECOGNITION_API_URL }}
            GOOGLE_CLIENT_ID=${{ env.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ env.GOOGLE_CLIENT_SECRET }}
            GOOGLE_REDIRECT_URL=${{ env.GOOGLE_REDIRECT_URL }}
            GOOGLE_SCOPES=${{ env.GOOGLE_SCOPES }}
            OAUTH2_STATE=${{ env.OAUTH2_STATE }}
            EOF
            chmod 600 ~/.carwisegw/carwisegw.env
            echo "✅ .env file created securely."

            echo "🚀 Running new container..."
            docker run -d --name carwisegw --restart always -p 4040:4040 \
              --env-file ~/.carwisegw/carwisegw.env \
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}